let usuarioActual=null;try{usuarioActual=JSON.parse(localStorage.getItem('usuarioActual')||'null');}catch(_){}
const rolActual=String((usuarioActual||{}).rol||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
if(!usuarioActual){location.href='../index.html';}
else if(!['super admin','super administrador','superadministrador'].includes(rolActual)){location.href='dashboard.html';}
else{
  document.getElementById('usuarioActual').textContent=(usuarioActual.nombre||usuarioActual.usuario||'')+' · '+(usuarioActual.rol||'');
  document.getElementById('btnVolver').onclick=()=>location.href='dashboard.html';
  document.getElementById('formUsuario').onsubmit=guardarUsuario;
  document.getElementById('formEditarUsuario').onsubmit=guardarCambios;
  document.getElementById('btnCerrarEditor').onclick=cerrarEditor;
  document.getElementById('btnCancelarEditor').onclick=cerrarEditor;
  document.getElementById('rol').addEventListener('change',()=>aplicarPermisosRol(''));
  document.getElementById('editRol').addEventListener('change',()=>aplicarPermisosRol('edit'));
  document.getElementById('filtroRol').addEventListener('change',renderizarUsuarios);
  document.getElementById('buscarUsuario').addEventListener('input',renderizarUsuarios);
  document.getElementById('formConfirmarEliminacion').onsubmit=confirmarEliminacion;
  document.getElementById('btnCancelarEliminacion').onclick=cerrarConfirmacionEliminacion;
  aplicarPermisosRol('');
  listarUsuarios();
}
function normalizarRol(rol){return String(rol||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function esSuperAdminRol(rol){const r=normalizarRol(rol);return['super admin','super administrador','superadministrador'].includes(r);}
function permisosFormulario(prefijo){return{usuarios:document.getElementById(prefijo+'permUsuarios').checked,movilidad:document.getElementById(prefijo+'permMovilidad').checked,fiscalizacion:document.getElementById(prefijo+'permFiscalizacion').checked,auditoria:document.getElementById(prefijo+'permAuditoria').checked};}
function setPermisosFormulario(p,prefijo){p=p||{};['usuarios','movilidad','fiscalizacion','auditoria'].forEach(k=>{const e=document.getElementById(prefijo+'perm'+k.charAt(0).toUpperCase()+k.slice(1));if(e)e.checked=p[k]===true;});forzarUsuariosSiSuperAdmin(prefijo);}
function rolSeleccionado(prefijo){return normalizarRol(document.getElementById(prefijo+'rol').value);}
function forzarUsuariosSiSuperAdmin(prefijo){const e=document.getElementById(prefijo+'permUsuarios');if(e&&esSuperAdminRol(rolSeleccionado(prefijo)))e.checked=true;}
function aplicarPermisosRol(prefijo){const p=window.SGTPermisos?window.SGTPermisos.defaults(rolSeleccionado(prefijo)):{};setPermisosFormulario(p,prefijo);}
function obtenerUsuariosFiltrados(){const datos=window._usuariosSGT||[],filtro=(document.getElementById('filtroRol')||{}).value||'todos',busqueda=((document.getElementById('buscarUsuario')||{}).value||'').trim().toLowerCase();return datos.filter(u=>{const coincideRol=filtro==='todos'||normalizarRol(u.rol)===normalizarRol(filtro);const texto=[u.nombre,u.usuario,u.rol].map(x=>String(x||'').toLowerCase()).join(' ');return coincideRol&&(!busqueda||texto.includes(busqueda));});}
function renderizarUsuarios(){const body=document.getElementById('tablaUsuarios');body.replaceChildren();const lista=obtenerUsuariosFiltrados();const contador=document.getElementById('contadorUsuarios');if(contador)contador.textContent=lista.length+' usuario'+(lista.length===1?'':'s');lista.forEach(u=>{const tr=document.createElement('tr');const p=u.permisos||{};const acceso=['usuarios','movilidad','fiscalizacion','auditoria'].filter(k=>p[k]).map(k=>({usuarios:'Usuarios',movilidad:'Movilidad Urbana',fiscalizacion:'Fiscalización',auditoria:'Auditoría'}[k])).join(', ')||'Sin módulos';tr.innerHTML='<td></td><td></td><td></td><td class="acceso-cell"></td><td></td><td><button class="btn-editar" type="button">Editar</button> <button class="btn-eliminar" type="button">Eliminar</button></td>';const c=tr.children;c[0].textContent=u.nombre||'';c[1].textContent=u.usuario||'';c[2].textContent=u.rol||'';c[3].textContent=acceso;c[4].textContent=u.activo||'';c[5].querySelector('.btn-editar').onclick=()=>abrirEditor(u);c[5].querySelector('.btn-eliminar').onclick=()=>eliminarUsuario(u);body.append(tr);});}
async function listarUsuarios(){const r=await apiObtenerUsuarios(),body=document.getElementById('tablaUsuarios');body.replaceChildren();if(!r.ok){mensaje(r.mensaje,'error');return;}window._usuariosSGT=r.datos||r.usuarios||[];renderizarUsuarios();}
async function guardarUsuario(ev){ev.preventDefault();const r=await apiGuardarUsuario({nombre:valor('nombre'),usuario:valor('usuario'),password:valor('password'),rol:valor('rol'),beta:valor('beta'),activo:valor('activo'),permisos:JSON.stringify(permisosFormulario(''))});if(!r.ok){mensaje(r.mensaje,'error');return;}ev.target.reset();aplicarPermisosRol('');mensaje(r.mensaje,'exito');listarUsuarios();}
function abrirEditor(u){document.getElementById('editorUsuario').hidden=false;document.getElementById('editId').value=u.id;document.getElementById('editNombre').value=u.nombre||'';document.getElementById('editUsuario').value=u.usuario||'';document.getElementById('editUsuario').dataset.original=u.usuario||'';document.getElementById('editPassword').value='';document.getElementById('editBeta').value=String(u.beta||'SI').toUpperCase()==='NO'?'NO':'SI';document.getElementById('editActivo').value=['no','false','0','inactivo'].includes(String(u.activo||'').trim().toLowerCase())?'NO':'SI';document.getElementById('editRol').value=u.rol||'Fiscalización';document.getElementById('editorSubtitulo').textContent='Editando '+(u.usuario||u.nombre||'usuario');setPermisosFormulario(u.permisos||{},'edit');document.getElementById('mensajeEditor').textContent='';}
function cerrarEditor(){document.getElementById('editorUsuario').hidden=true;}
async function guardarCambios(ev){ev.preventDefault();const usuarioOriginal=String(document.getElementById('editUsuario').dataset.original||'').trim();const usuarioNuevo=valor('editUsuario');const r=await apiActualizarUsuario({id:valor('editId'),usuarioOriginal:usuarioOriginal||usuarioNuevo,usuario:usuarioNuevo,nombre:valor('editNombre'),password:valor('editPassword'),rol:valor('editRol'),activo:valor('editActivo'),beta:valor('editBeta'),permisos:JSON.stringify(permisosFormulario('edit'))});const e=document.getElementById('mensajeEditor');if(!r.ok){e.textContent=r.mensaje;e.className='error';return;}e.textContent=r.mensaje;e.className='exito';setTimeout(()=>{cerrarEditor();listarUsuarios();},500);}
function eliminarUsuario(u){if(String(u.usuario||'').trim().toLowerCase()===String(usuarioActual.usuario||'').trim().toLowerCase()){mensaje('No puede eliminar su propio usuario.','error');return;}const superObjetivo=esSuperAdminRol(u.rol);document.getElementById('eliminarId').value=u.id;document.getElementById('eliminarId').dataset.usuario=u.usuario||'';document.getElementById('passwordConfirmacion').value='';document.getElementById('mensajeEliminacion').textContent='';document.getElementById('mensajeEliminacion').className='';document.getElementById('textoConfirmacion').textContent='¿Confirma la eliminación del usuario '+(u.usuario||'')+'?';const aviso=document.getElementById('avisoSeguridad'),campo=document.getElementById('passwordConfirmacion');aviso.hidden=!superObjetivo;campo.required=superObjetivo;campo.disabled=!superObjetivo;campo.placeholder=superObjetivo?'Ingrese la contraseña actual del Super Admin':'';document.getElementById('confirmarEliminacion').hidden=false;if(superObjetivo)campo.focus();}
function cerrarConfirmacionEliminacion(){document.getElementById('confirmarEliminacion').hidden=true;document.getElementById('formConfirmarEliminacion').reset();}
async function confirmarEliminacion(ev){ev.preventDefault();const el=document.getElementById('eliminarId'),usuario=el.dataset.usuario||'',superObjetivo=!document.getElementById('passwordConfirmacion').disabled,passwordConfirmacion=superObjetivo?valor('passwordConfirmacion'):'';const e=document.getElementById('mensajeEliminacion');e.textContent='Verificando...';e.className='';const r=await apiEliminarUsuario(usuario,passwordConfirmacion);if(!r.ok){e.textContent=r.mensaje;e.className='error';if(r.codigo==='PASSWORD_OBJETIVO_INVALIDA'||r.codigo==='REQUIERE_PASSWORD_OBJETIVO')document.getElementById('passwordConfirmacion').focus();return;}cerrarConfirmacionEliminacion();mensaje(r.mensaje,'exito');listarUsuarios();}
function valor(id){const e=document.getElementById(id);return e?e.value.trim():'';}function mensaje(t,c){const e=document.getElementById('mensaje');if(e){e.textContent=t;e.className=c||'';}}
